version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-qa
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-qa-data:/var/lib/postgresql/data

  backend:
    build:
      context: ../BackendUdemyPro-main
      dockerfile: Dockerfile
    container_name: backend-qa
    restart: always
    depends_on:
      - postgres
    ports:
      - "9002:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build:
      context: ../FrontendUdemyPro-main
      dockerfile: Dockerfile
    container_name: frontend-qa
    restart: always
    ports:
      - "4201:80"
    depends_on:
      - backend

volumes:
  postgres-qa-data:
