version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: backend-dev
    restart: always
    depends_on:
      - postgres
    ports:
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    container_name: frontend
    build:
      context: ../../FrontendUdemyPro-main
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://localhost:3100
    volumes:
      - ../../FrontendUdemyPro-main:/app
      - /app/node_modules

volumes:
  postgres-data:
