services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: ../../BackendUdemyPro-main
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  frontend:
    container_name: frontend
    build:
      context: ../../FrontendUdemyPro-main
      dockerfile: Dockerfile
    ports:
      - "80:4200"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=${BACKEND_URL}

volumes:
  postgres-data:
